# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'proj1.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(844, 516)
        self.lcd_temp = QtWidgets.QLCDNumber(Dialog)
        self.lcd_temp.setGeometry(QtCore.QRect(40, 70, 231, 101))
        self.lcd_temp.setObjectName("lcd_temp")
        self.label_temp = QtWidgets.QLabel(Dialog)
        self.label_temp.setGeometry(QtCore.QRect(70, 20, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_temp.setFont(font)
        self.label_temp.setObjectName("label_temp")
        self.lcd_humidity = QtWidgets.QLCDNumber(Dialog)
        self.lcd_humidity.setGeometry(QtCore.QRect(520, 70, 231, 101))
        self.lcd_humidity.setObjectName("lcd_humidity")
        self.label_humidity = QtWidgets.QLabel(Dialog)
        self.label_humidity.setGeometry(QtCore.QRect(570, 20, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_humidity.setFont(font)
        self.label_humidity.setObjectName("label_humidity")
        self.lineEdit_ts = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_ts.setGeometry(QtCore.QRect(330, 310, 151, 32))
        self.lineEdit_ts.setObjectName("lineEdit_ts")
        self.label_ts = QtWidgets.QLabel(Dialog)
        self.label_ts.setGeometry(QtCore.QRect(360, 340, 101, 22))
        self.label_ts.setObjectName("label_ts")
        self.pushButton_refresh = QtWidgets.QPushButton(Dialog)
        self.pushButton_refresh.setGeometry(QtCore.QRect(350, 250, 99, 30))
        self.pushButton_refresh.setObjectName("pushButton_refresh")
        self.pushButton_tempgraph = QtWidgets.QPushButton(Dialog)
        self.pushButton_tempgraph.setGeometry(QtCore.QRect(60, 450, 271, 41))
        self.pushButton_tempgraph.setObjectName("pushButton_tempgraph")
        self.pushButton_humgraph = QtWidgets.QPushButton(Dialog)
        self.pushButton_humgraph.setGeometry(QtCore.QRect(530, 450, 271, 41))
        self.pushButton_humgraph.setObjectName("pushButton_humgraph")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(30, 260, 68, 22))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(560, 260, 68, 22))
        self.label_5.setObjectName("label_5")
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(390, 30, 20, 201))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.checkBox_temp = QtWidgets.QCheckBox(Dialog)
        self.checkBox_temp.setGeometry(QtCore.QRect(120, 180, 101, 27))
        self.checkBox_temp.setObjectName("checkBox_temp")
        self.lineedit_maxtemp = QtWidgets.QLineEdit(Dialog)
        self.lineedit_maxtemp.setGeometry(QtCore.QRect(110, 250, 113, 32))
        self.lineedit_maxtemp.setObjectName("lineedit_maxtemp")
        self.lineedit_maxhum = QtWidgets.QLineEdit(Dialog)
        self.lineedit_maxhum.setGeometry(QtCore.QRect(640, 250, 113, 32))
        self.lineedit_maxhum.setObjectName("lineedit_maxhum")
        self.alarm = QtWidgets.QTextEdit(Dialog)
        self.alarm.setGeometry(QtCore.QRect(180, 370, 501, 75))
        self.alarm.setObjectName("alarm")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(27, 390, 111, 22))
        self.label.setObjectName("label")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_temp.setText(_translate("Dialog", "Temperature"))
        self.label_humidity.setText(_translate("Dialog", "Humidity"))
        self.label_ts.setText(_translate("Dialog", "Time stamp"))
        self.pushButton_refresh.setText(_translate("Dialog", "Refresh"))
        self.pushButton_tempgraph.setText(_translate("Dialog", "Generate Graph for temperature"))
        self.pushButton_humgraph.setText(_translate("Dialog", "Generate Graph for Humidity"))
        self.label_4.setText(_translate("Dialog", "Max limit"))
        self.label_5.setText(_translate("Dialog", "Max limit"))
        self.checkBox_temp.setText(_translate("Dialog", "Celcius"))
        self.label.setText(_translate("Dialog", "Notifications"))

